
apiVersion: v1
kind: ConfigMap
metadata:
  name: indy-config
  labels:
    app: indy-node
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  indy_config.py: |-
    # Current network
    NETWORK_NAME = '{{ .Values.network_name }}'
    # Directory to store ledger.
    LEDGER_DIR = '/var/lib/indy'

    # Directory to store logs.
    LOG_DIR = '/var/log/indy'

    # Directory to store keys.
    KEYS_DIR = '/var/lib/indy'

    # Directory to store genesis transactions files.
    GENESIS_DIR = '/var/lib/indy'

    # Directory to store backups.
    BACKUP_DIR = '/var/lib/indy/backup'

    # Directory to store plugins.
    PLUGINS_DIR = '/var/lib/indy/plugins'

    # Directory to store node info.
    NODE_INFO_DIR = '/var/lib/indy'