{{- range $node := .Values.nodes }}
---
apiVersion: v1
kind: Secret
metadata:
  name: indy-seed-{{ $node.alias }}
  labels:
    app: indy-node
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    node: {{ $node.alias }}
type: Opaque
data:
  seed: {{ $node.seed | b64enc | quote }}
{{- end }}